SNAP-14222 & SNAP-14223: Convert terraform to pulumi & Update GitHub Actions
seconddinner/stress-test-loader pull request #29
Opened 2023-06-01 20:04 UTC by wwu-sd

1. Convert the Terraform code to Pulumi & c# code to set up infrastructure on AWS for the stress test loader.
    - Uses Pulumi "Automation API"(https://www.pulumi.com/docs/using-pulumi/automation-api/)
    - Uses the scaffolding from @jcoakley-sd 
    - Supports creating infrastructure in one or more AWS regions
2. Add a simple stress test client.
    - Written in dotnet.
    - Pings a host and logs the result.
    - Number of pings, interval between pings, and host name configurable through environment variables.
3. Update the GitHub Actions workflow to fully automate the stress test.
    - Based on the existing integration test workflow.
    - Uses Pulumi to get the IP addresses of the created EC2 instances instead of AWS CLI.
    - Move environment variables from the workflow yaml to the repo's environment settings.
    - The workflow basically does the following things:
        (1) Set up the AWS account
        (2) Use Pulumi to deploy the infrastructure for the stress test loader
        (3) Build the simple stress test client and upload the executable to S3
        (4) Use the golang stress test loader to start the test through GRPC calls
        (5) Sleep for n seconds (wait until the stress test is done)
        (6) Use Pulumi to destroy the infrastructure

Thanks to @jxie-sd and @jcoakley-sd for the help!

2023-06-01 23:18 UTC, jxie-sd requested changes

2023-06-01 23:18 UTC, jxie-sd commented on .github/workflows/intergration-test.yml
> +    #container: seconddinner/build:0.0.5
we will need to fix this asap. maybe in a different branch

2023-06-01 23:18 UTC, jxie-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Ami.cs
> +        var stl = new Aws.Ec2.AmiCopy("stl-" + region, new Aws.Ec2.AmiCopyArgs
we will need to build image to multi regions

2023-06-01 23:18 UTC, jxie-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +      ""Resource"": ""arn:aws:s3:::stresstest-client/*""
make is a variable and make is configurable & note in readme.

2023-06-01 23:18 UTC, jxie-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/stressclient-template.sh
> +curl -X POST "https://register.zone2.seconddinnertech.net/v1/server/1xCrmez3Xy34qKg4h99RUgqVbQR6sUPVmYSTc0TE1rJYLmgKKpwnOshC1Ejvc2YM/" -H  "accept: application/json" -H  "content-type: application/js
comment this out. We will address this when we build the controller

2023-06-01 23:18 UTC, jxie-sd commented on .github/workflows/intergration-test.yml
> +    #container: seconddinner/build:0.0.5
no action needed

2023-06-02 16:32 UTC, wwu-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +      ""Resource"": ""arn:aws:s3:::stresstest-client/*""
env var added

2023-06-02 16:32 UTC, wwu-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/stressclient-template.sh
> +curl -X POST "https://register.zone2.seconddinnertech.net/v1/server/1xCrmez3Xy34qKg4h99RUgqVbQR6sUPVmYSTc0TE1rJYLmgKKpwnOshC1Ejvc2YM/" -H  "accept: application/json" -H  "content-type: application/js
commented

2023-06-02 16:44 UTC, jxie-sd submitted a review, later dismissed

2023-06-02 20:34 UTC, jcoakley-sd requested changes

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/DeployHelpers.cs
> +        };
Consider using a managed config object for these. That way, you could configure everything upfront in Program.cs. I recommend removing lines 86-92 and 98-123, leaving only `aws:region` and `aws-native:region` which are required by their respective plugins.

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Infra.Pulumi.csproj
> +
You're going to need to copy the stressclient-template.sh file into the output directory here. Otherwise, the template rendering in Autoscaling.cs will fail.

```
 	<ItemGroup>
	  <None Update="Resources/stressclient-template.sh" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
```

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Program.cs
> +            }
This could probably be simplified to:
```
var regions = Environment.GetEnvironmentVariable("regions") ?? "us-west-2";
var regionList = regions.Split(',').ToList();
```

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Program.cs
> +                    iam.StressTestClientReadProfileName,vpc.MainVpcId, vpc.DefaultSecurityGroupId,
`vpc.DefaultSecurityGroupId` isn't used

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Ami.cs
> +    [Output]
These tags are redundant, despite being all over the official documentation

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Ami.cs
> +    public Ami(string name, Aws.Provider provider, string region, ComponentResourceOptions opts = null) : base("stl:aws:Ami", name, opts)
If you refactor the config to use a custom object, you could reduce this constructor to just `public Ami(StressConfig cfg, ComponentResourceOptions opts)`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +        var cirdBlocks = new InputList<string>
*cidrBlocks

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +        var stress_test_loader_allowed_cidr = config.Require("stress_test_loader_allowed_cidr");
rule of thumb: if a variable is simple and used only once, consider removing it:
```
var cidrBlocks = new InputList<string>
{
    config.Require("stress_test_loader_allowed_cidr")
}
```

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +        };
same note as above

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
If you specify the Parent here, you don't need to specify the Provider

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +          Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +          Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +          Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +                Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +                Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Ami.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            Provider = provider,
`new CustomResourceOptions { Parent = this });`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +    public Aws.AutoScaling.Group group;
None of these gets used

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +        // vpcZoneIdentifiers.AddRange(mainSubnet.Select(__item => __item.Id).ToList());
Remove old comments

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +            }
This should probably be removed. We want to reset the content of /tmp/IP.json with the IPs of the current ec2 instances, right?

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Autoscaling.cs
> +                File.WriteAllText(filePath, json);
Consider simplifying to:
```
File.WriteAllText(filePath, JsonSerializer.Serialize(instancesList));
```

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +        var currentRegion = Output.Create(Aws.GetRegion.InvokeAsync());
These don't get used

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +        var stressTestClientReadRole = new Aws.Iam.Role("stressTestClientReadRole-" + region, new Aws.Iam.RoleArgs
Consider folding the RolePolicy into the Role definition by setting `Role.InlinePolicies`

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +        var stressTestClientReadRole = new Aws.Iam.Role("stressTestClientReadRole-" + region, new Aws.Iam.RoleArgs
Consider using `Amazon.Auth.AccessControlPolicy`'s `Policy` class to construct iam policies:
```
               AssumeRolePolicy = new Policy().WithStatements(
                    new Statement(Statement.StatementEffect.Allow)
                        .WithId(null)
                        .WithActionIdentifiers(new ActionIdentifier("sts:AssumeRole"))
                        .WithPrincipals(new Principal(Principal.SERVICE_PROVIDER, "ec2.amazonaws.com"))
                        .WithConditions(assumeRolePolicyCondition))
                    .ToJson(),
```

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Iam.cs
> +      ""Resource"": ""arn:aws:s3:::" + s3_client_bucket_name + @"/*""
Where do these buckets get created? Should we be controlling them via this pulumi project?

2023-06-02 20:34 UTC, jcoakley-sd commented on infra-pulumi/Infra.Pulumi/Infra.Pulumi/Resources/Vpc.cs
> +    public Output<string> ReplaceIPandCIDR(Output<string> input, int rangeIndex)
Can be made `private`

2023-06-02 20:35 UTC, jcoakley-sd commented
A custom config object class might look like:

2023-06-06 18:00 UTC, jcoakley-sd requested changes

2023-06-06 20:04 UTC, jcoakley-sd approved these changes

2023-06-06 20:39 UTC, merged