[Luoweichao] support logging via EFK stack
seconddinner/stress-test-loader pull request #7
Opened 2022-09-06 17:39 UTC by chaosreload

1. add es-domain module to setup OpenSearch service
2. update user_data.sh to setup filebeat and rsyslogd

2022-09-13 11:12 UTC, chaosreload commented
Just updated:
1. setup more shards for the index to spread the requests evenly to the data nodes
2. process json inside filebeat
3. remove the problematic 'aws_subnet_ids'

2022-09-15 08:54 UTC, jxie-sd requested changes

2022-09-15 08:54 UTC, jxie-sd commented on infra-terraform/instance/single-region-with-efk/providers.tf
> +    profile = "aws_aws-cube-nvstressclient-bd-us_app.luoweichao"
we can't not have this profile in the source code

2022-09-15 08:54 UTC, jxie-sd commented on infra-terraform/instance/single-region-with-efk/providers.tf
> +  profile = "aws_aws-cube-nvstressclient-bd-us_app.luoweichao"
we can't not have this profile in the source code

2022-09-15 08:55 UTC, jxie-sd commented
I'm looking at this PR. I don't know if we can just merge [infra-terraform/instance/single-region-with-efk ](https://github.com/seconddinner/stress-test-loader/pull/7/files#diff-2ed3c9a2ac2a7aaede3015cb81e17536beefc50c96b1c2e01d2a4082fc8f6481) into [infra-terraform/instance/single-region ](https://github.com/seconddinner/stress-test-loader/pull/7/files#diff-2ed3c9a2ac2a7aaede3015cb81e17536beefc50c96b1c2e01d2a4082fc8f6481) and make ES a variable, and if it's turned on, add ES.

what is the use of infra-terraform/opensearch-domain

2022-09-26 20:12 UTC, jxie-sd requested changes

2022-09-26 20:12 UTC, jxie-sd commented on infra-terraform/terraform-modules/iam/iam.tf
> +                "secretsmanager:GetSecretValue",
why does the terraform EC2 need to read secrets? can we limit to smaller subset of the secret?

2022-09-26 20:12 UTC, jxie-sd commented on infra-terraform/terraform-modules/iam/iam.tf
> +                "secretsmanager:GetSecretValue",
do something like following is a lot safer

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "arn:aws:secretsmanager:us-west-2:111122223333:secret:aes128-1a2b3c",
                "arn:aws:secretsmanager:us-west-2:111122223333:secret:aes192-4D5e6F",
                "arn:aws:secretsmanager:us-west-2:111122223333:secret:aes256-7g8H9i"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "secretsmanager:ListSecrets",
            "Resource": "*"
        }
    ]
}

2022-09-26 20:13 UTC, jxie-sd commented
you need to rebase on master to resolve conflict

2022-09-26 22:18 UTC, jxie-sd commented
-var 'create_esdomain=false' will produce: 

│ Error: your query returned no results
│ 
│   with data.aws_elasticsearch_domain.es[0],
│   on es-domain.tf line 15, in data "aws_elasticsearch_domain" "es":
│   15: data "aws_elasticsearch_domain" "es" {
│

2022-09-27 11:06 UTC, chaosreload commented on infra-terraform/terraform-modules/iam/iam.tf
> +                "secretsmanager:GetSecretValue",
I wanted to store the password of Kibana in the secretsmanager, so I added those related policies. I'll limit the affected resources only to the password

2022-09-27 11:11 UTC, chaosreload commented
> 

I follow these steps to create the PR:
1. edit codes in forked luoweichao branch
2. commit and push to origin
3. create PR from 'luoweichao' branch to main branch in upstream

Could you share the operation to rebase on main branch?

2022-09-27 11:13 UTC, chaosreload commented
> │ Error: your query returned no results

It fails when you specify  'create_esdomain=false' and a non-exist ElasticSearch domain. You can specify an existing ElasticSearch domain in the 'esdomain' variable or create a new one by specifying 'create_esdomain=true'.

2022-09-28 16:30 UTC, jxie-sd commented on infra-terraform/terraform-modules/iam/iam.tf
> +                "secretsmanager:GetSecretValue",
got it. make sense. Let limit only for certain resources that Kibana needs

2022-09-28 16:32 UTC, jxie-sd commented
@chaosreload Like what we discussed, we need a control variable that take out ES domains, so it doesn't even build the ES in sometimes.

2022-09-29 18:54 UTC, jxie-sd approved these changes
approve this for now. 

We still need to work on create_esdomain = false part

2022-09-29 18:54 UTC, merged